name: gnucash-cm
title: GnuCash
version: "5.12-2"
summary: Personal and small-business financial-accounting software.
description: |
  Designed to be easy to use, yet powerful and flexible, GnuCash allows you to
  track bank accounts, stocks, income and expenses. As quick and intuitive to
  use as a checkbook register, it is based on professional accounting principles
  to ensure balanced books and accurate reports.

base: core24
confinement: strict
grade: devel

platforms:
  amd64:

layout:
  /usr/local/share:
    bind: $SNAP/usr/local/share
  /usr/share/gnucash:
    bind: $SNAP/usr/share/gnucash
  /usr/share/guile:
    bind: $SNAP/usr/share/guile
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/guile:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/guile
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dbd:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dbd
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gnucash:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gnucash
  /usr/bin/finance-quote-wrapper:
    bind-file: $SNAP/usr/bin/finance-quote-wrapper


parts:
  gnucash-app:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DWITH_SQL=ON
      - -DWITH_AQBANKING=OFF
      - -DWITH_PYTHON=OFF
      - -DGNUCASH_BUILD_ID=5.12-snap
    source: https://github.com/Gnucash/gnucash/releases/download/5.12/gnucash-5.12.tar.gz
    source-checksum: sha256/fa279ac0378b1860ede15a8b6645628e17e7e94df496d69be8fd5d20a570ccc7
    build-packages:
      - g++
      - make
      - git
      - pkg-config
      - libgtest-dev
      - libelf-dev
#      - libxml2-dev
#      - libxml2-utils
      - libxslt1-dev
#      - libgtk-4-dev
#      - libglib2.0-dev
#      - libwebkit2gtk-4.1-dev
      - swig
      - guile-3.0-dev
      - libofx-dev
      - xsltproc
      - libboost-dev
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libboost-locale-dev
      - libboost-regex-dev
      - libboost-system-dev
      - libboost-program-options-dev
      - libdbi-dev
      - libdbd-sqlite3
#      - libsecret-1-dev
#      - zlib1g-dev
#      - texinfo
#      - dh-python
#      - locales-all
#      - imagemagick
#      - gettext
    stage-packages:
      - guile-3.0
#      - libgtk-4-1
#      - libglib2.0-0
      - libboost-date-time1.83.0
      - libboost-filesystem1.83.0
      - libboost-locale1.83.0
      - libboost-regex1.83.0
      - libboost-system1.83.0
      - libboost-thread1.83.0
      - libboost-program-options1.83.0
#      - libsecret-1-0
      - libxslt1.1
#      - libwebkit2gtk-4.1-0
      - libdbi1
      - libofx7t64
#      - libdbd-pgsql
#      - libdbd-mysql
      - libdbd-sqlite3
#      - locales-all
      - perl
      - libfinance-quote-perl
      - libdate-manip-perl
      - libproxy1v5
      - libxml-sax-perl
    override-prime: |
      craftctl default
    
      # Remove the external symlink
      rm -f $CRAFT_PRIME/usr/share/perl5/XML/SAX/ParserDetails.ini

  gnucash-desktop-icon:
    after:
      - gnucash-app
    plugin: nil
    override-prime: |
      craftctl default
      sed -i 's|^Icon=.*|Icon=/usr/share/icons/hicolor/scalable/apps/gnucash-icon.svg|' usr/share/applications/gnucash.desktop


environment:
  LC_ALL: "C.UTF-8"
  PERL5LIB: "$SNAP/usr/share/perl5/:$SNAP/usr/share/perl/5.38.2/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl/5.38.2/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl5/5.38.2"


apps:
  gnucash:
    extensions: [ gnome ]
    command: usr/bin/gnucash
    desktop: usr/share/applications/gnucash.desktop
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gnucash
    plugs:
      - network
      - home
  gnucash-cli :
    command: usr/bin/gnucash-cli
    plugs: [network, home]